---
title: "Exercises 2"
author: "Doug Goon"
date: "April 27, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. 
(a)
```{r}
A <- matrix(
  c(1, 5, -2, 1, 2, -1, 3, 6, -3),
  nrow = 3,
  ncol = 3
  )
A
```

```{r}
A%%A%%A
```

(b)
```{r}
A[,3] <- A[,2] + A[,3]
A
```

2.
```{r}
B <- matrix( 
  c(10,-10,10),
  byrow = TRUE,
  ncol = 3,
  nrow = 15
  )
crossprod(B)
```

3.
```{r}
matE <- matrix(
  0,
  nrow = 6,
  ncol = 6
)
matE[abs(col(matE)-row(matE))==1] <- 1
matE
```

4.
```{r}
a <- 0:4
A <- outer(a,a,"+")
A
```

5. 
(a)
```{r}
outer(0:4,0:4,"+")%%5
```

(b)
```{r}
outer(0:9,0:9,"+")%%10
```

(c)
```{r}
outer(0:8,0:8,"-")%%9
```

6.
```{r}
ymatrix <- c(7, -1, -3, 5, 17)
Amatrix <- matrix(0,nr=5,nc=5)
Amatrix <- abs(col(Amatrix)-row(Amatrix))+1
xmatrix <- solve(Amatrix,ymatrix)
xmatrix
```

7.
```{r}
set.seed(75)  
aMat <- matrix(sample(10, size=60, replace=TRUE), nr=6)  
aMat
```

(a)
```{r}
apply(aMat, 1, function(x){sum(x>4)})
```

(b)
```{r}
which( apply(aMat, 1,function(x){sum(x==7)==2}))
```

(c)
```{r}
which( outer(colSums(aMat),colSums(aMat),"+")>75, arr.ind=T )
```

What if repetitions are not permitted?
```{r}
aMatColSums <- colSums(aMat)
logicalMat <- outer(aMatColSums,aMatColSums,"+")>75
logicalMat[lower.tri(logicalMat,diag=T)] <- F
which(logicalMat, arr.ind=T)
```

8.
(a)
```{r}
sum((1:20)^4) * sum(1/(3+(1:5)))
```

(b)
```{r}
sum((1:20)^4 / (3 + outer(1:20,1:5,"*")))
```

(c)
```{r}
sum(outer(1:10,1:10,function(i,j){ (i>=j)*i^4/(3+i*j) }))
```

